### ISSUE TITLE
Can we add input mapping support on-demand service?

### ISSUE THREAD

**Issue by dwu-pivotal** [pivotal-cf/on-demand-services-sdk#3]
E.g. For a service that use keepalived to do high availability.  One additional IP address(this address can not be managed by bosh) need to be assigned to each deployment.
The use case looks like tihs:
1. An operator inputs a IP range (e.g. 192.168.0.1 to 192.168.0.100) in Ops Manager for that on-demand service tile.
2. A user creates a service, and our broker picks up a value in that IP range(e.g. 192.168.0.1), and assigns to this deployment.
3. A user deletes a service, and our broker releases that IP (e.g. 192.168.0.1) .

To support this requirement, what we need to implement is:
1. persistent storage (E.g. a internal database )  to store used and available data
2. Events: create service sucessfully/failed, and service is deleted. to notify our service adapter to allocate/release the IP( and any values that needs managed)

**Comment by kieron-pivotal** [comment]
Hi @dwu-pivotal  - sorry for the huge delay in responding.

Is this still an issue for you? Have you considered whether a post-deploy and pre-delete errand combination would solve this for you?

- Kieron (with @kirederik)
