### ISSUE TITLE
Add support for advanced BOSH agent configuration for an instance group

### ISSUE THREAD

**Issue by RMeharg** [pivotal-cf/on-demand-services-sdk#9]
I have a service adapter that needs to make use of the advanced BOSH agent configuration, however currently the InstanceGroups struct does not support the `env [Hash, optional]` functionality of BOSH.

See: https://github.com/pivotal-cf/on-demand-services-sdk/blob/master/bosh/bosh_manifest.go#L46

Specifically I need to configure the BOSH agent instance group with both `string` and `bosh [Hash, optional]` values

The generated manifest would look something like:
```
env:
  bosh:
    swap_size: 0
  persistent_disk_fs: xfs
```

You can look at https://bosh.io/docs/manifest-v2.html for more info on the advanced BOSH agent configuration.

**Comment by avade** [comment]
This is now scheduled, but we may not get to it before the holidays.

We are open to a PR for this as well. Please ensure the appropriate tests are also updated if you go down this route.

**Comment by terminatingcode** [comment]
@RMeharg @avade we are going to begin working on this story now.

**Comment by kieron-pivotal** [comment]
The code has been delivered in commit a2bc2ef5.

We allow an arbitrary hash for the `env` property, which will allow both the documented `bosh` hash and any other undocumented properties such as `persistent_disk_fs` to be passed, as in the example manifest snippet above.

**Comment by RMeharg** [comment]
Thanks! I will wait for the next release then implement for the customer.

**Comment by deniseyu** [comment]
@RMeharg Closing this issue as this work seems to be done.
